FROM continuumio/miniconda3

WORKDIR /app

# Set environment variables for dev environment
ENV PYTHONUNBUFFERED=1

# Copy just the conda environment file first
COPY environment.yml ./

# Create the conda environment
RUN conda env create -v -f environment.yml

# Copy remaining files to workdir
COPY . .

CMD conda run --no-capture-output -vvv -n breaching uvicorn main:app --host 0.0.0.0 --port 8000 --reload
