FROM continuumio/anaconda3

WORKDIR /root

RUN apt-get clean && apt-get update

# install various packages to help manage python,
# testing, linting, coverage, formatting and project management
RUN pip install pytest && \
    pip install pytest-cov && \
    pip install poetry && \
    pip install ruff

# for the backend api stuff
RUN pip install uvicorn && \
    pip install fastapi
    
# install git additions
RUN apt-get install git-flow -y && \
    pip install pre-commit && \
    pip install conventional-commit
   
# change shell to zsh and install useful commandline tools
RUN apt-get install zsh vim htop tree fzf -y && \
    chsh -s /bin/zsh && \
    zsh && \
    sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
    git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions && \
    echo "source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh" >> "/root/.zshrc"
SHELL ["/bin/zsh", "-c"]

# install nvm, npm, node and react stuff
RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash && \
    export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
    nvm install 18 && nvm use 18 &&\npm install -g next@latest react@latest react-dom@latest
