FROM continuumio/anaconda3

WORKDIR /root

# install gcc and git-flow
RUN apt-get clean && apt-get update && apt-get install gcc git-flow -y

COPY environment.yml .

RUN conda env create -v -f environment.yml

# change shell to zsh and install useful commandline tools
RUN apt-get install zsh vim htop tree fzf -y && \
    chsh -s /bin/zsh && \
    zsh && \
    sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
    git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions && \
    echo "source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh" >> "/root/.zshrc"
SHELL ["/bin/zsh", "-c"]

# install nvm, npm, node and react stuff
RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash && \
    export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
    nvm install 18 && nvm use 18 &&\npm install -g next@latest react@latest react-dom@latest

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "privacy-ml-container", "/bin/bash", "-c"]

# Set the default command to bash
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "privacy-ml-container", "/bin/bash"]
