name: CD

on:
  push:
    # branches:
    #   - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure SSH and pull updated containers
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        command_timeout: 30m
        script: |
          # Navigate to dir containing docker-compose
          cd ~

          # Pull the latest Docker images from the registry
          docker-compose pull

          # Recreate and restart containers
          docker-compose up -d